### ISSUE TITLE
Segment Violation - OSX

### ISSUE THREAD

**Issue by mubix** [sensepost/ruler#6]
Using OSX/Brew to install Go
Then ran ruler:
```
./ruler -v -domain company.com
[*] Retrieving MAPI/HTTP info
[*] Doing Autodiscover for domain
[*] Autodiscover step 0 - URL: https://company.com/autodiscover/autodiscover.xml
[*] Autodiscover step 1 - URL: https://autodiscover.company.com/autodiscover/autodiscover.xml
[*] Autodiscover step 2 - URL: http://autodiscover.company.com/autodiscover/autodiscover.xml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8dd9a]

goroutine 1 [running]:
panic(0x2f5f00, 0xc4200100b0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/sensepost/ruler/autodiscover.autodiscover(0x7fff5fbffc40, 0xa, 0xc4204c0001, 0x0, 0x0, 0x0)
	/home/mubix/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:149 +0x31a
github.com/sensepost/ruler/autodiscover.autodiscover(0x7fff5fbffc40, 0xa, 0xc420134001, 0x0, 0x0, 0x0)
	/home/mubix/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:180 +0x40c
github.com/sensepost/ruler/autodiscover.autodiscover(0x7fff5fbffc40, 0xa, 0x1, 0x0, 0x0, 0x0)
	/home/mubix/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:144 +0xabb
github.com/sensepost/ruler/autodiscover.MAPIDiscover(0x7fff5fbffc40, 0xa, 0x1, 0x1e, 0x0)
	/home/mubix/go/src/github.com/sensepost/ruler/autodiscover/autodiscover.go:64 +0xbc
main.getMapiHTTP(0x0, 0x0, 0x0)
	/sensepost/ruler/ruler.go:48 +0xe2
main.main()
	/sensepost/ruler/ruler.go:145 +0x947
```

Manually going to those addresses results in:
```
[*] Autodiscover step 0 - URL: https://company.com/autodiscover/autodiscover.xml
> 404
[*] Autodiscover step 1 - URL: https://autodiscover.company.com/autodiscover/autodiscover.xml
> Auth required
[*] Autodiscover step 2 - URL: http://autodiscover.company.com/autodiscover/autodiscover.xml
> Connection refused
```

**Comment by staaldraad** [comment]
Hi Rob

Thanks for the report.

Can you try to force the second URL (which seems to be the correct one):

```
./ruler -v -url https://autodiscover.company.com/autodiscover/autodiscover.xml -user XXX -pass YYY
```

I'm trying to replicate now, I can see where and why the SegFault is happening, I just don't see what is causing it.

**Comment by mubix** [comment]
Seems to have gotten farther, thanks!
```
[x] The autodiscover service request did not complete.
[x] Permission Denied or URL not found: StatusCode [401]
```

**Comment by staaldraad** [comment]
Fixed in https://github.com/sensepost/ruler/commit/cd0420b5ce8fa9f8050f2b3d9a4630af89ecbd0a
