### ISSUE TITLE
RPC URL set should be https

### ISSUE THREAD

**Issue by braaaax** [sensepost/ruler#75]
I am unable to set a channel to port 443, which is open. 'RPC URL set' instead points to port 80, which is filtered. I am reasoning this is the case because of the error: `... RPC Setup Err: dial tcp 10.7.12.10:80: getsockopt: connection timed out`. This makes sense as port 80 is indeed filtered. Is there a way to set a channel to 443 (ie RPC URL set: https://blahblah)?

```
./ruler-linux64 --insecure --nocache --domain DOMAIN  --username 'USER' --email "EMAIL" --verbose check
Password:
[+] Retrieving MAPI/HTTP info
[*] Autodiscover step 0 - URL: https://autodiscover.DOMAIN/autodiscover/autodiscover.xml
[*] RPC URL set: http://MAIL.DOMAIN/rpc/rpcproxy.dll?fea6b5b5-35c3-421e-8144-69f0548694bb@DOMAIN:6001
[*] Setting up channels
ERROR: 16:34:20 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. mapi: a transport layer error occurred. Couldn't setup RPC channel - RPC Setup Err: dial tcp 10.7.12.10:80: getsockopt: connection timed out
```

**Comment by staaldraad** [comment]
Hi! 

You can modify the "cached" `autodiscover.xml` file, or use the `--config` option: https://github.com/sensepost/ruler/wiki/Getting-Started#the-config-file

The config file is probably what you want, it allows you to directly specify the RPC URL. It seems like the autodiscover record returned by the server has RPC set as http.

Hope this helps!

**Comment by braaaax** [comment]
Hi, thanks for the reply. 
Not sure how to modify the cached autodiscover.xml file. I've tried the --nocache option as well as setting the -url manually. I've also tried with config.yml, setting rpcurl to "https://mx01.lab.local/rpc/rpcproxy.dll?fea6b5b5-35c3-421e-8144-69f0548694bb@lab.local:6001." This brings me a step forward to Bind RPC but I still get the errors:
```ERROR: 12:49:11 rpctransport.go:574: RPC Timeout                                                                                                                                                             
ERROR: 12:49:11 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. Invalid HTTP response: [HTTP/1.1 401 Unauthorized]```

I haven't used the config.yml before and perhaps I've made an error there. Thanks for your help

**Comment by staaldraad** [comment]
It looks like the Authentication is failing, likely that you need to play around with ntlm vs basic auth in the config file.
Modifying the cache file is also straight forward, in the ruler directory, there is a folder called `logs`, in there you should see a file called `email_domain.cache` (where email_domain matches the target user), open that in a text editor and find the RPC url and change the `http` to `https`.

hope that helps!

**Comment by braaaax** [comment]
Thanks again for your help. I've tried a lot of variations in the config file and seem to have taken another step further. I'm sorry for the length of my response.My results are summarized below with a markup of the relevant console output beneath. 

- rpc:true/ntlm:false I get an error, unable to obtain session context, and asked to try again with the --encrypt flag (there is no such flag to my knowledge)
- rpc:true/ntlm:false I get 401 unathorized
- rpc:false/ntlm:true I get protocol error response 10
- rpc:false/btlm:false I get protocol error response 10

```
# ❯❯❯ ./ruler-linux64 --config config.yml --verbose --insecure --nocache display
[*] Setting up channels
[+] Binding to RPC
ERROR: 01:08:44 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC.
Unable to obtain a session context
Try again using the --encrypt flag. It is possible that the target requires 'Encrypt traffic between Outlook and Exchange' to be enabled

# ❯❯❯ cat config.yml
username: "rortiz"
email: "rortiz@lab.local"
password: "Autumn2017!"
hash: ""
domain: "lky.local"
userdn: "/o=lab/ou=Exchange AdministrativeGroup (FYDIBOHF23SPDLT)/cn=Recipients/cn=ef03ae59640a44c995d2dc6e62668b2f-Robert Ortiz"
mailbox: "fea6b5b5-35c3-421e-8144-69f0548694bb@lab.local"
rpc: true
rpcencrypt: true
ntlm: true
rpcurl: "https://mx01.lab.local/rpc/rpcproxy.dll"
mapiurl: "https://mx01.lab.local/mapi/emsmdb/"

# ❯❯❯ ruler --config config.yml --verbose --insecure check
[*] Setting up channels
[+] Binding to RPC
ERROR: 01:57:24 rpctransport.go:574: RPC Timeout
ERROR: 01:57:24 ruler.go:29: mapi: a transport layer error occurred. An error occurred setting up RPC. Invalid HTTP response: [HTTP/1.1 401 Unauthorized]

...
rpc: true
ntlm: false
...

# ❯❯❯ ./ruler-linux64 --config config.yml --verbose --insecure --nocache display
[*] User DN:  /o=lab/ou=Exchange AdministrativeGroup (FYDIBOHF23SPDLT)/cn=Recipients/cn=ef03ae59640a44c995d2dc6e62668b2f-Robert Ortiz
[*] Got Context, Doing ROPLogin
ERROR: 01:11:02 ruler.go:29: mapi: a transport layer error occurred. Got a protocol error response: 10

# ❯❯❯ cat config.yml 
...
rpc: false
ntlm: true
...

# ❯❯❯ ./ruler-linux64 --config config.yml --verbose --insecure --nocache display
[*] User DN:  /o=lab/ou=Exchange AdministrativeGroup (FYDIBOHF23SPDLT)/cn=Recipients/cn=ef03ae59640a44c995d2dc6e62668b2f-Robert Ortiz
[*] Got Context, Doing ROPLogin
ERROR: 01:12:36 ruler.go:29: mapi: a transport layer error occurred. Got a protocol error response: 10

# ❯❯❯ cat config.yml
...
rpc: false
ntlm: false
...
```

**Comment by staaldraad** [comment]
Getting there! 

Thanks for the detailed response! Really appreciate it, it makes it so much easier to try and figure out what is going on :smile: Exchange comes in so many configurations it gets tough to figure out what the issue could be.

First thought would be this config, with the domain set to empty 
```
domain: ""
<..snip...>
rpc: true
rpcencrypt: true
ntlm: true
```  

The protocol 10 errors are coming from MAPI/HTTP. Which I think indicates that MAPI/HTTP isn't enabled for that user. I'm not :100: sure, it has been a while since I saw that particular error. This can be set in the Exchange Admin Interface, /ecp I think. Under the use's settings there is a remote mail option. Really can't recall what it is called off the top of my head, it does say MAPI/HTTP in the description.

Hope this gets you a little further! Ruler is normally pretty good at figuring this stuff out automatically

**Comment by braaaax** [comment]
Thanks! I wanted to give as much info as possible. I've been trying the tool on a test lab Active Directory with the goal to pivot to another trust where 'rortiz' is also a user. Below is the debug info with the configuration you mentioned previously. Not sure I understand 'CMX01.lab.locaHIMicrosoft..'
UnknownUserException is interesting. I went to double check the info I have for the user was correct (it is, taken from the legacyexchangedn property).

I wanted to take advantage of the ability for Ruler do as much as it can automatically, but I can't seem to edit the log file correctly. I have logs in the same directory as the binary. There was no RPCUrl entry, so I added one, but neither the elf nor the go binary uses the entry I've added. (I've attached a copy of the file below.) 

I appreciate you help with all of this!

```# ❯❯❯ ./ruler-linux64 --config config.yml --verbose --debug  display                       
[*] Setting up channels                          
[+] Binding to RPC                               
O                                                            
CMX01.lab.locaHIMicrosoft.Exchange.RpcClientAccess.Server.UnknownUserException: Unable to map userDn '/o=lab/ou=Exchange AdministrativeGroup (FYDIBOHF23SPDLT)/cn=Recipients/cn=ef03ae59640a44c995d2dc6e62668b2f-Robert Ortiz' to exchangePrincipal (StoreError=UnknownUser) ---> Microsoft.Exchange.Data.Storage.ObjectNotFoundException: The Active Directory user wasn't found.                                        
   at Microsoft.Exchange.Data.Storage.ExchangePrincipal.<>c__DisplayClass14.<FromLegacyDNByMiniRecipient>b__13()
   at Microsoft.Exchange.Data.Storage.DirectoryHelper.DoAdCallAndTranslateExceptions(Action call, String methodName)
   at Microsoft.Exchange.Data.Storage.ExchangePrincipal.FromLegacyDNByMiniRecipient(ADSessionSettings adSettings, String legacyDN, RemotingOptions remotingOptions, PropertyDefinition[] miniRecipientPropert
ies, MiniRecipient& miniRecipient)                                                                     
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.<>c__DisplayClass2.<FindExchangePrincipal>b__0()
   at Microsoft.Exchange.Data.Storage.DirectoryHelper.DoAdCallAndTranslateExceptions(Action call, String methodName)
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.FindExchangePrincipal(String legacyDN, String userDomain, MiniRecipient& miniRecipient)
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.User.UpdatePrincipalCacheIfNeeded()
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.User.UpdatePrincipalCacheWrapped(Boolean ignoreCrossForestMailboxErrors)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.User.UpdatePrincipalCacheWrapped(Boolean ignoreCrossForestMailboxErrors)
   at Microsoft.Exchange.RpcClientAccess.Server.UserManager.Get(SecurityIdentifier authenticatedUserSid, String actAsLegacyDN, String userDomain)
   at Microsoft.Exchange.RpcClientAccess.Server.RpcDispatch.<>c__DisplayClassc.<EcDoConnectEx>b__8()
   at Microsoft.Exchange.RpcClientAccess.Server.RpcDispatch.Execute(Func`1 getExecuteParameters, Func`1 executeDelegate, Action`1 exceptionSerializationDelegate)!
{{5 0 2 3 10 8d0 10 5} 94080000010000007607925eeed6d19bfe21d57d39407a20f76a92678ad83c99b493cb43d04032a5cc6ca22501b2f2cc8d87e (very long hash to follow ...)```

rortiz_lab_local.cache:
(I've added the `<RPCUrl>https://mx01.lab.local/rpc/rpcproxy.dll</RPCUrl>`)
```<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
  <Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
    <User>
      <DisplayName>Robert Ortiz</DisplayName>
      <LegacyDN>/o=lab/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=ef03ae59640a44c995d2dc6e62668b2f-Robert Ortiz</LegacyDN>
      <AutoDiscoverSMTPAddress>ROrtiz@lab.local</AutoDiscoverSMTPAddress>
      <DeploymentId>e057cf20-d7f0-40bf-9e48-81d7b108c68a</DeploymentId>
    </User>
    <Account>
      <AccountType>email</AccountType>
      <Action>settings</Action>
      <MicrosoftOnline>False</MicrosoftOnline>
      <Protocol>
        <Type>EXCH</Type>
        <Server>fea6b5b5-35c3-421e-8144-69f0548694bb@lab.local</Server>
        <ServerDN>/o=lab/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=fea6b5b5-35c3-421e-8144-69f0548694bb@lab.local</ServerDN>
        <ServerVersion>73C0834F</ServerVersion>
        <MdbDN>/o=lab/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=fea6b5b5-35c3-421e-8144-69f0548694bb@lab.local/cn=Microsoft Private MDB</MdbDN>
        <PublicFolderServer>mx01.lab.local</PublicFolderServer>
        <AD>DC01.lab.local</AD>
        <ASUrl>https://mx01.lab.local/EWS/Exchange.asmx</ASUrl>
        <EwsUrl>https://mx01.lab.local/EWS/Exchange.asmx</EwsUrl>
        <EmwsUrl>https://mx01.lab.local/EWS/Exchange.asmx</EmwsUrl>
        <EcpUrl>https://mx01.lab.local/ecp/</EcpUrl>
        <EcpUrl-um>?rfr=olk&amp;p=customize/voicemail.aspx&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-um>
        <EcpUrl-aggr>?rfr=olk&amp;p=personalsettings/EmailSubscriptions.slab&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-aggr>
        <EcpUrl-mt>PersonalSettings/DeliveryReport.aspx?rfr=olk&amp;exsvurl=1&amp;IsOWA=&lt;IsOWA&gt;&amp;MsgID=&lt;MsgID&gt;&amp;Mbx=&lt;Mbx&gt;&amp;realm=lab.local</EcpUrl-mt>
        <EcpUrl-ret>?rfr=olk&amp;p=organize/retentionpolicytags.slab&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-ret>
        <EcpUrl-sms>?rfr=olk&amp;p=sms/textmessaging.slab&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-sms>
        <EcpUrl-publish>customize/calendarpublishing.slab?rfr=olk&amp;exsvurl=1&amp;FldID=&lt;FldID&gt;&amp;realm=lab.local</EcpUrl-publish>
        <EcpUrl-photo>PersonalSettings/EditAccount.aspx?rfr=olk&amp;chgPhoto=1&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-photo>
        <EcpUrl-tm>?rfr=olk&amp;ftr=TeamMailbox&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-tm>
        <EcpUrl-tmCreating>?rfr=olk&amp;ftr=TeamMailboxCreating&amp;SPUrl=&lt;SPUrl&gt;&amp;Title=&lt;Title&gt;&amp;SPTMAppUrl=&lt;SPTMAppUrl&gt;&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-tmCreating>
        <EcpUrl-tmEditing>?rfr=olk&amp;ftr=TeamMailboxEditing&amp;Id=&lt;Id&gt;&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-tmEditing>
        <EcpUrl-extinstall>Extension/InstalledExtensions.slab?rfr=olk&amp;exsvurl=1&amp;realm=lab.local</EcpUrl-extinstall>
        <OOFUrl>https://mx01.lab.local/EWS/Exchange.asmx</OOFUrl>
        <UMUrl>https://mx01.lab.local/EWS/UM2007Legacy.asmx</UMUrl>
        <OABUrl>https://mx01.lab.local/OAB/17671d75-4a3a-45f6-9e65-77ba64c8e93b/</OABUrl>
        <RPCUrl>https://mx01.lab.local/rpc/rpcproxy.dll</RPCUrl>
        <ServerExclusiveConnect>off</ServerExclusiveConnect>
      </Protocol>
      <Protocol>
        <Type>EXPR</Type>
        <Server>mx01.lab.local</Server>
        <SSL>Off</SSL>
        <AuthPackage>Ntlm</AuthPackage>
        <ServerExclusiveConnect>on</ServerExclusiveConnect>
        <CertPrincipalName>None</CertPrincipalName>
        <GroupingInformation>Default-First-Site-Name</GroupingInformation>
      </Protocol>
      <Protocol>
        <Type>WEB</Type>
        <Internal>
          <OWAUrl AuthenticationMethod="Basic, Fba">https://mx01.lab.local/owa/</OWAUrl>
          <Protocol>
            <Type>EXCH</Type>
            <ASUrl>https://mx01.lab.local/EWS/Exchange.asmx</ASUrl>
            <RPCUrl>https://mx01.lab.local/rpc/rpcproxy.dll</RPCUrl>
          </Protocol>
        </Internal>
      </Protocol>
    </Account>
  </Response>
</Autodiscover>
```
